/*
 * generated by Xtext
 */
package fr.imta.tp.selenium.ui.contentassist

import fr.imta.tp.selenium.ui.contentassist.AbstractSeleniumProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SeleniumProposalProvider extends AbstractSeleniumProposalProvider {
}
