/*
 * generated by Xtext
 */
package fr.imta.tp.selenium;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SeleniumRuntimeModule extends fr.imta.tp.selenium.AbstractSeleniumRuntimeModule {

}
