/*
* generated by Xtext
*/
package fr.imta.tp.selenium;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SeleniumStandaloneSetup extends SeleniumStandaloneSetupGenerated{

	public static void doSetup() {
		new SeleniumStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

