/*
* generated by Xtext
*/
package fr.imta.tp.selenium;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SeleniumUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return fr.imta.tp.selenium.ui.internal.SeleniumActivator.getInstance().getInjector("fr.imta.tp.selenium.Selenium");
	}
	
}
