/**
 * generated by Xtext
 */
package fr.imta.tp.selenium.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class SeleniumQuickfixProvider extends DefaultQuickfixProvider {
}
