/*
 * generated by Xtext
 */
package fr.imta.tp.selenium.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.imta.tp.selenium.ui.internal.SeleniumActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SeleniumExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SeleniumActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SeleniumActivator.getInstance().getInjector(SeleniumActivator.FR_IMTA_TP_SELENIUM_SELENIUM);
	}
	
}
