/**
 * generated by Xtext
 */
package fr.imta.tp.selenium.validation;

import fr.imta.tp.selenium.validation.AbstractSeleniumValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SeleniumValidator extends AbstractSeleniumValidator {
}
