/*
 * generated by Xtext
 */
package fr.imta.tp.selenium.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SeleniumUiModule extends fr.imta.tp.selenium.ui.AbstractSeleniumUiModule {
	public SeleniumUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
