/*
* generated by Xtext
*/
package fr.imta.tp.selenium.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SeleniumAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("fr/imta/tp/selenium/parser/antlr/internal/InternalSelenium.tokens");
	}
}
